import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.base import Base


class NotificationKind(str, enum.Enum):
    announcement = "announcement"
    attendance_risk = "attendance_risk"
    grade_posted = "grade_posted"
    general = "general"


class Notification(Base):
    """A per-user notification. Generated by the backend (e.g. fanned out
    when an announcement is posted, or raised when attendance drops below a
    threshold) rather than posted directly by users."""

    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    kind: Mapped[NotificationKind] = mapped_column(
        Enum(NotificationKind, name="notification_kind"), default=NotificationKind.general
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    is_read: Mapped[bool] = mapped_column(Boolean, default=False)

    # optional pointer to whatever this notification is about (an enrollment
    # id for attendance_risk, an announcement id for announcement, etc.) —
    # lets callers dedupe/reference precisely without parsing free text
    related_id: Mapped[uuid.UUID | None] = mapped_column(nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
